#!/usr/bin/env bash

source "$(dirname $0)/../util"

meval rs00  27017 'db.getSiblingDB("rsmap").runCommand("dbHash").collections'
meval rs01  27017 'db.getSiblingDB("rsmap").runCommand("dbHash").collections'
meval rs02  27017 'db.getSiblingDB("rsmap").runCommand("dbHash").collections'
meval extra 27018 'db.getSiblingDB("rsmap").runCommand("dbHash").collections'

qc=$(cat "$(dirname "$0")/../quickcheck.js")
meval rs00  27017 "$qc"
meval extra 27018 "$qc"

echo "# mongo:27017"
mongosh "mongo:27017" --quiet --eval "$qc"
